export enum AppActions {
  FETCH_COMPANIES = 'FETCH_COMPANIES',
  FETCH_EMPLOYEES = 'FETCH_EMPLOYEES',
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  ADD_PROJECT = 'ADD_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  SET_NODE_SELECTED = 'SET_NODE_SELECTED',
  SET_COMPANY_ADDRESS = 'SET_COMPANY_ADDRESS',
}

export const API_URL = 'http://localhost:3005';
